version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 10
    groups:
      azure-sdk:
        patterns:
          - "Azure.*"
      opentelemetry:
        patterns:
          - "OpenTelemetry.*"
          - "Microsoft.Azure.Functions.Worker.OpenTelemetry"
      functions-worker:
        patterns:
          - "Microsoft.Azure.Functions.Worker*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: "Europe/London"
    open-pull-requests-limit: 5
